apiVersion: apps/v1
kind: Deployment
metadata: 
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: web
          image: examen:0.1
          ports:
            - containerPort: 8080