name: ci-cd

on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas
        run: npm test

  deploy:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Construir imagen Docker
        run: docker build -t app:${{ github.sha }} .

      - name: Simular despliegue
        run: echo "Despliegue autorizado porque las pruebas terminaron correctamente"